# Generated by Django 4.0.3 on 2022-03-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="post",
            name="timestamp",
        ),
    ]
